app_main/urls.py
from django.urls import path
from . import views
app_name = 'main'
urlpatterns = [
    path('',views.home,name="home"),
    path('login',views.login_view, name="login"),
    path('signup',views.signup_view,name="signup"),
    path('logout',views.logout_view,name="logout")
]

walletTree/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('app_main.urls'))
]

app_main/models.py
from django.db import models

# Create your models here.

app_main/views.py
from django.shortcuts import render,redirect,HttpResponse
from django.contrib.auth.models import User
from django.contrib.auth import login,authenticate,logout
from django.contrib import messages
from . import manager

# Create your views here.
def home(request):
    
    return render(request, "home.html")

def login_view(request):
    if request.method == "POST":
        username = request.POST.get("username")
        password = request.POST.get("password")
        
        # Use authenticate() to check credentials properly
        user = authenticate(request, username=username, password=password)
        
        if user is not None:
            login(request, user)
            print("login was successful")
            messages.success(request, f"welcome {user.username},")
            return redirect('main:home')  # Redirect after successful login
        else:
            messages.error(request, "Invalid username or password.")
    
    return render(request, 'login.html')

def signup_view(request):
    if request.method == "POST":
        try:
            username = request.POST.get("username")
            password = request.POST.get("password")
            email = request.POST.get("email")
            u = User.objects.create_user(username=username,email=email,password=password)
            u.save()
            messages.success(request,"welcome to wallettree, pls login.")
        except Exception as e:
            messages.error(request,e)


        return redirect("main:login")
    return render(request,"signup.html")

def logout_view(request):
    logout(request)
    messages.success(request,"you have been succesfully logged out")
    return redirect("main:login")

app_main/templates/home.html
{% extends 'layout.html' %}
{% load static %}
{% block header %}
    <link rel="stylesheet" href="{% static 'styles/home.css' %}">
    <script src="{%static 'scripts/home.js'%}" defer></script>
{% endblock %}
{% block pagename %}
    home
{% endblock %}
{% block body %}
<div class="page-container">
    
    <div class="news-container">
        <div class="news-card"></div>
        <div class="news-card"></div>
        <div class="news-card"></div>
        <div class="news-card"></div>
        <div class="news-card"></div>
        <div class="news-card"></div>
        <div class="news-card"></div>
        <div class="news-card"></div>
        <div class="news-card"></div>
        <div class="news-card"></div>
        <div class="news-card"></div>
    </div>
    {% if messages %}
    <div class="message-container">
        {% for message in messages %}
        <div class="message {{message.tags}}">
            {{message}}
        </div>
            
        {% endfor %}
    </div>
    {%endif%}

</div>

{% endblock %}

app_main/templates/layout.html
<!doctype html>
<html lang="en">
    {% load static %}
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'styles/layout_style.css' %}">
    <!-- <script type="text/javascript" src="{%static 'scripts/layout_script.js'%}" defer></script> -->
    
    {% block header %}
        
    {% endblock %}
    <title>WalletTree | {% block pagename %}{% endblock %} </title>
  </head>
  <body>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>


    <div class="layout-container">


  <div class="navbar-container {% if request.user.is_authenticated %}user-auth{% else %}user-guest{% endif %}">

        <nav>

          <ul>
            <li>
              <a href="{% url 'main:home' %}">WalletTree</a>
            </li>
            <li>
              
              <a href="{% url 'main:home' %}">
                <svg xmlns="http://www.w3.org/2000/svg" height="24px" viewBox="0 -960 960 960" width="24px" ><path d="M240-200h120v-240h240v240h120v-360L480-740 240-560v360Zm-80 80v-480l320-240 320 240v480H520v-240h-80v240H160Zm320-350Z"/></svg>Home</a>
            </li>

            <li>
              <a href="#">
              <svg xmlns="http://www.w3.org/2000/svg" height="24px" viewBox="0 -960 960 960" width="24px" ><path d="M560-440q-50 0-85-35t-35-85q0-50 35-85t85-35q50 0 85 35t35 85q0 50-35 85t-85 35ZM280-320q-33 0-56.5-23.5T200-400v-320q0-33 23.5-56.5T280-800h560q33 0 56.5 23.5T920-720v320q0 33-23.5 56.5T840-320H280Zm80-80h400q0-33 23.5-56.5T840-480v-160q-33 0-56.5-23.5T760-720H360q0 33-23.5 56.5T280-640v160q33 0 56.5 23.5T360-400Zm440 240H120q-33 0-56.5-23.5T40-240v-440h80v440h680v80ZM280-400v-320 320Z"/></svg>
                Transactions</a>
            </li>

            <li>
              <a href="#">
              <svg xmlns="http://www.w3.org/2000/svg" height="24px" viewBox="0 -960 960 960" width="24px" ><path d="M200-120q-33 0-56.5-23.5T120-200v-640h80v640h640v80H200Zm40-120v-360h160v360H240Zm200 0v-560h160v560H440Zm200 0v-200h160v200H640Z"/></svg>
                Stock</a>
            </li>
            {% if request.user.is_authenticated %}
              
            <li>

            <a href="{% url 'main:logout' %}">
              <svg xmlns="http://www.w3.org/2000/svg" height="24px" viewBox="0 -960 960 960" width="24px" fill="white"><path d="M200-120q-33 0-56.5-23.5T120-200v-560q0-33 23.5-56.5T200-840h280v80H200v560h280v80H200Zm440-160-55-58 102-102H360v-80h327L585-622l55-58 200 200-200 200Z"/></svg>
              logout</a>
            </li>
            
            {% endif %}


            {% if request.user.is_authenticated %}
            <li>
              <a href="#">
                <svg xmlns="http://www.w3.org/2000/svg" height="24px" viewBox="0 -960 960 960" width="24px" fill="white"><path d="M234-276q51-39 114-61.5T480-360q69 0 132 22.5T726-276q35-41 54.5-93T800-480q0-133-93.5-226.5T480-800q-133 0-226.5 93.5T160-480q0 59 19.5 111t54.5 93Zm246-164q-59 0-99.5-40.5T340-580q0-59 40.5-99.5T480-720q59 0 99.5 40.5T620-580q0 59-40.5 99.5T480-440Zm0 360q-83 0-156-31.5T197-197q-54-54-85.5-127T80-480q0-83 31.5-156T197-763q54-54 127-85.5T480-880q83 0 156 31.5T763-763q54 54 85.5 127T880-480q0 83-31.5 156T763-197q-54 54-127 85.5T480-80Zm0-80q53 0 100-15.5t86-44.5q-39-29-86-44.5T480-280q-53 0-100 15.5T294-220q39 29 86 44.5T480-160Zm0-360q26 0 43-17t17-43q0-26-17-43t-43-17q-26 0-43 17t-17 43q0 26 17 43t43 17Zm0-60Zm0 360Z"/></svg>
                hi, {{request.user.username|lower}}
              </a>
            </li>
            {% else %}
            <li>
              <a href="{% url 'main:login' %}">
                  <svg xmlns="http://www.w3.org/2000/svg" height="24px" viewBox="0 -960 960 960" width="24px" fill="white"><path d="M234-276q51-39 114-61.5T480-360q69 0 132 22.5T726-276q35-41 54.5-93T800-480q0-133-93.5-226.5T480-800q-133 0-226.5 93.5T160-480q0 59 19.5 111t54.5 93Zm246-164q-59 0-99.5-40.5T340-580q0-59 40.5-99.5T480-720q59 0 99.5 40.5T620-580q0 59-40.5 99.5T480-440Zm0 360q-83 0-156-31.5T197-197q-54-54-85.5-127T80-480q0-83 31.5-156T197-763q54-54 127-85.5T480-880q83 0 156 31.5T763-763q54 54 85.5 127T880-480q0 83-31.5 156T763-197q-54 54-127 85.5T480-80Zm0-80q53 0 100-15.5t86-44.5q-39-29-86-44.5T480-280q-53 0-100 15.5T294-220q39 29 86 44.5T480-160Zm0-360q26 0 43-17t17-43q0-26-17-43t-43-17q-26 0-43 17t-17 43q0 26 17 43t43 17Zm0-60Zm0 360Z"/></svg>
                  signup/login
              </a>
            </li>
            {% endif %}

          </ul>

        </nav>

      </div>
     {% block body %}
      
    {% endblock %}
    </div>


  </body>
</html>

app_main/templates/login.html
{% extends 'layout.html' %}
{% load static %}
{% block header %}
    <link rel="stylesheet" href="{% static 'styles/login.css' %}">
    <link rel="stylesheet" href="{% static 'styles/singup.css' %}">


{% endblock %}
{% block pagename %}
    login
{% endblock %}

{% block body %}
    <div class="content-container">



        <form action="{% url 'main:login' %}" method="POST">
            {% csrf_token %}
            <div class="title">
                <h2>
                    <a href="{% url 'main:login' %}" id="active">login</a> | <a href="{% url 'main:signup' %}">signup</a>
                </h2>
            </div>
            <label for="username">username</label>
            <input type="text" name="username">
            <label for="password">password</label>
            <input type="password" name="password">

            <button type="submit">submit</button>
                    {% if messages %}
            <div class="messages-container">
                {% for message in messages %}
                    <div class="message {{message.tags}}">
                        {{ message }}
                    </div>
                {% endfor %}
            </div>
        {% endif %}


        </form>
    </div>
{% endblock %}

app_main/templates/signup.html
{% extends 'layout.html' %}
{% load static %}
{% block header %}
    <link rel="stylesheet" href="{% static 'styles/login.css' %}">

{% endblock %}
{% block pagename %}
    login
{% endblock %}

{% block body %}
    <div class="content-container">



        <form action="{% url 'main:signup' %}" method="POST">
            {% csrf_token %}
            <div class="title">
                <h2><a href="{% url 'main:login' %}" >login</a> | <a href="{% url 'main:signup' %}" id="active">signup</a></h2>
            </div>
            <label for="username">username</label>
            <input type="text" name="username">
            <label for="username">email</label>
            <input type="email" name="email">
            <label for="password">password</label>
            <input type="password" name="password">

            <button type="submit">submit</button>
                    {% if messages %}
            <div class="messages-container">
                {% for message in messages %}
                    <div class="message {{message.tags}}">
                        {{ message }}
                    </div>
                {% endfor %}
            </div>
        {% endif %}

        </form>
    </div>
{% endblock %}